---
- name: 'Playbook_0'
  hosts: vm
  remote_user: azureuser
  become: true
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world