---
- name: Install apache httpd  (state=present is optional)
  hosts: vm
  remote_user: azureuser
  become: true
  tasks: 
    - name: 'Apache2'
      ansible.builtin.apt:
        name: apache2
        state: present

    #NO FUNCIONA.. VERIFICAR
    - name: 'permitir trafico web'
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        inmediate: yes