---
- name: Create credentials file for webserver authentication
  hosts: vm
  remote_user: azureuser
  become: true
  tasks:
      - name: Install passlib with pip
        ansible.builtin.apt:
          update_cache: yes
          name: python3-passlib          
      - name: Creating credentials file 
        community.general.htpasswd:
          path: /etc/apache/passwdfile
          name: unir
          password: unir
          